# Build stage
FROM node:20-slim AS build-stage
WORKDIR /app
COPY marketing/package*.json ./
RUN npm install
COPY marketing/ ./
RUN npm run build

# Production stage
FROM nginx:stable-alpine AS production-stage
COPY --from=build-stage /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
