apiVersion: v1
kind: Secret
metadata:
  name: {{ include "specterdefence.fullname" . }}-secrets
  labels:
    {{- include "specterdefence.labels" . | nindent 4 }}
type: Opaque
stringData:
  secretKey: {{ .Values.secrets.secretKey | quote }}
