apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: specterdefence-data
  labels:
    app.kubernetes.io/name: specterdefence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path