{{/*
API Server Pod Disruption Budget
*/}}
{{- if and .Values.api.enabled .Values.api.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "specterdefence.apiFullname" . }}
  labels:
    {{- include "specterdefence.apiLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "specterdefence.apiSelectorLabels" . | nindent 6 }}
  {{- if .Values.api.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.api.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.api.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.api.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
