{{/*
Frontend Pod Disruption Budget
*/}}
{{- if and .Values.frontend.enabled .Values.frontend.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "specterdefence.frontendFullname" . }}
  labels:
    {{- include "specterdefence.frontendLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "specterdefence.frontendSelectorLabels" . | nindent 6 }}
  {{- if .Values.frontend.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.frontend.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.frontend.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.frontend.podDisruptionBudget.maxUnavailable }}
  {{- end }}
{{- end }}
